pyrs/core/mantid_fit_peak.py
pyrs/core/peak_collection.py
tests/unit/test_hidra_project_file.py

Since peak objects shouldn't hold multiple profile functions, move that into the constructor.

Move common parameters into constructor

---

pyrs/core/nexus_conversion.py

It happens that the sample log starts to record after run starts. So do not raise exception on this scenario in nexus conversion.

Loose the requirement on DAS

---

pyrs/core/nexus_conversion.py
scripts/reduce_HB2B.py
tests/integration/test_autoreduction.py

In #193 it was noted that the first splitter doesn't wait until the motor has stopped moving. This compares the logs to their setpoints and finds when the log first gets to the setpoint (within tolerance). This is supposed to be fixed in the DAS before the next runcycle, but shouldn't have an effect if everything is working problem.

Motors stop moving

---

pyrs/core/nexus_conversion.py

It was discovered that `EventWorkspace` has an overhead of 440bytes per spectrum when it is created. This meant that the memory usage of setting up the output of [`FilterEvents`](https://docs.mantidproject.org/nightly/algorithms/FilterEvents-v1.html) created ~44GB of empty `EventWorkspaces` before attempting to filter them. This changes the behavior to filter out each subrun separately and convert that to a histogram workspace of significantly smaller size.

Reduce the number of event workspaces that exist at a single time

---

pyrs/peaks/mantid_fit_peak.py
tests/unit/test_peak_fit_engine.py

This requires [mantid PR27809](https://github.com/mantidproject/mantid/pull/27809) before the pseudo-Voigt will actually work. However, this change won't break the currently working Gaussian peak fitting so it is safe to merge.
Fixes #293

Specify default mixing parameter only

---

pyrs/interface/peak_fitting/event_handler.py
pyrs/interface/peak_fitting/gui_utilities.py

In the fit table, an exception is created after the data is fitted, before the the table is viewed.

Allow for not having selected row

---

pyrs/core/peak_profile_utility.py
tests/unit/test_peak_collection.py

@peterfpeterson @JeanBilheux pointed out a copy/paste error where error arrays contained values. This corrects those oversights.

Point to error array instead of value array

---

pyrs/utilities/file_util.py
tests/unit/test_utilities.py

This is a workaround while the `.ORIG.nxs.h5` files still exist for some of the runs.

Fall back to finddata when ArchiveSearch fails

---

pyrs/core/mantid_helper.py

This is also technically wrong, but will give more reasonable weighting to the data for fitting than setting all uncertainties to zero.

Add sqrt(y) as the uncertainties

---

.travis.yml
README.rst
requirements.txt
requirements_dev.txt
setup.py

This should reduce the number of places to update the list of requirements for the package. `mantid-workbench` is supplied separately since developer builds will often use mantid built locally rather than the `mantid-workbench` package.

Move requirements into standard text files for re-use

---

pyrs/core/nexus_conversion.py
scripts/reduce_manual_HB2B.py
tests/unit/test_splitter.py

The issue came from runs where the run did not end with `scan_index=0`. This solution is to add an ending time 1 day into the future.
Fixes #471

Create Splitter without end time

---

pyrs/projectfile/file_object.py
tests/unit/test_hidra_project_file.py

Before this was set on reading the peaks the wavelength was just NaN and therefore d-spacing and strain were also NaN

Set the wavelength when reading PeakCollection from file

---

pyrs/dataobjects/fields.py
pyrs/projectfile/file_object.py
pyrs/utilities/file_util.py
tests/unit/pyrs/dataobjects/test_fields.py

This adds code for creating a `StrainField` directly from a project file. It does not currently support multiple peaks in a single project file.
Refs #427

StrainField from project file

---

pyrs/dataobjects/fields.py
pyrs/projectfile/file_object.py
tests/unit/pyrs/dataobjects/test_fields.py

Since the GUI will need to create a project file to determine what peak tags are available, add an option to the constructor to re-use it.
Refs #427

Create StrainField from project file

---

tests/unit/pyrs/dataobjects/test_fields.py

Impose ordering in test of stacking scalar fields

---

pyrs/dataobjects/sample_logs.py
tests/unit/pyrs/dataobjects/test_sample_logs.py

DirectionExtents with a list of coordinates containing only one unique value

---

pyrs/interface/strainstressviewer/strain_stress_view.py

Now only the model is replaced when the workspace changed, a new SliceViewer instance isn't created. This means the slice selection, colorbar selection is preserved when the workspace changes
Part of #358

Change how the workspace is updated in the Strain/Stress viewer

---

pyrs/projectfile/file_object.py
tests/unit/test_hidra_project_file.py

Fixed a bug which stopped the Hidra Project File from writing peak data
if peak data already existed.
Fixes #512 
Signed-off-by: Robert Smith <smithrw@ornl.gov>

Hidra Projct File now supports overwritting peak data

---

pyrs/interface/strainstressviewer/strain_stress_view.py

Change default interpoltaion to bilinear in strain/stress viewer

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

Remove clone methods from classes in module dataobjects.field

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

Switch from StressField is a ScalarFieldSample to StrainField has a ScalarFieldSample

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

Turn stress components in StressField to ScalarFieldSamples

---

pyrs/dataobjects/fields.py

Export StrainField and StressField to MDHistoWorkspace with no intepolation

---

pyrs/interface/strainstressviewer/model.py
tests/ui/test_stress_strain_viewer.py

This should make sure no changes in the backend break the Stress/Strain UI

Add tests for the strain/stress viewer model

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

Export StrainField and StressField to MDHistoWorkspace with linear intepolation

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

The name was not set in the `__init__` function and was not being copied in the `stack_strain` method.
Fixes #601

Fix bug in finding copying the filenames when stacking

---

pyrs/dataobjects/fields.py
tests/integration/pyrs/dataobjects/test_fields.py
tests/unit/pyrs/dataobjects/test_fields.py

Add test data with multiple griding for StressField testing

---

pyrs/interface/peak_fitting/plot.py

When the 3D plot is shrunk to zero size the plotting failed. So don't try to plot if the height is 0.
Fixes #625

Peak fitting windows - Fix bug in trying to plot in a mpl figure of zero area

---

pyrs/projectfile/file_object.py
tests/unit/test_hidra_project_file.py

Unlike Python file objects, the attribute File.name gives the HDF5 name of the root group, “/”. To access the on-disk name, use File.filename.

Fix bug getting filename from HidraProjectFile

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

Add the ability to get/set the d-reference through the `StrainField`. Setting from a ScalarFieldSample is covered later by #664.
Refs #525

StrainField get/set d-reference

---

pyrs/core/summary_generator_stress.py

Get the field once so the value is only calculated once

Improve speed of stress field summary writing

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

The only operation that should invalidate the cache is setting the d-reference. There is a question as to whether the change to the unit test is correct.
Refs #525

Cache ScalarFieldSample in StrainFieldSingle

---

pyrs/dataobjects/fields.py
pyrs/dataobjects/sample_logs.py
tests/conftest.py
tests/test_conftest.py
tests/unit/pyrs/dataobjects/test_fields.py
tests/unit/pyrs/dataobjects/test_sample_logs.py

StrainField set d-reference from ScalarFieldSample

---

pyrs/dataobjects/fields.py
tests/unit/pyrs/dataobjects/test_fields.py

StressField set d-reference from ScalarFieldSample

---

pyrs/core/stress_facade.py
tests/unit/pyrs/core/test_stress_facade.py

Check setting the reference spacing in a multi-scan with different set of points along different directions

---

pyrs/core/stress_facade.py
tests/unit/pyrs/core/test_stress_facade.py

Include d_spacing_center as a peak parameter in the facade object

---

pyrs/core/stress_facade.py
pyrs/dataobjects/fields.py
tests/plot_sample_points.py
tests/unit/pyrs/core/test_stress_facade.py

Facade object should provide peak parameters along directions

---

pyrs/core/stress_facade.py
tests/unit/pyrs/core/test_stress_facade.py

StressFacade.peak_parameter should raise when selecting 33 in a surface scan

---

tests/ui/test_stress_strain_viewer.py

This fails as it requires mantidplot nightly version `>5.0`for the sliceviewer to work correctly. We need to fix the conda build for mantid workbench for the tests to pass.
This runs find for deployment to analysis as we use the system package.

Add UI tests for Strain/Stress viewer

---

pyrs/calibration/peakfit_calibration.py
pyrs/core/instrument_geometry.py
pyrs/core/nexus_conversion.py
pyrs/core/pyrscore.py
pyrs/core/reduce_hb2b_pyrs.py
pyrs/core/reduction_manager.py
pyrs/peaks/mantid_fit_peak.py
pyrs/projectfile/file_object.py
pyrs/utilities/calibration_file_io.py
tests/integration/test_powder_pattern.py

Refactor AnglerCamera to DENEX. plus a refactor of reduce_hb2b_pyrs to a single "import numpy as np" and not "import numpy and import numpy as np"

refactor AnglerCamera naming convention to DENEX

---

pyrs/interface/pyrs_main.py

A new instance will be created, thereby clearing any previous input
Fixes #749

Change how stress viewer is launched

---

pyrs.sh
pyrs/dataobjects/fields.py
pyrs/dataobjects/sample_logs.py
tests/unit/pyrs/dataobjects/test_fields.py
tests/unit/pyrs/dataobjects/test_sample_logs.py

**Work Done:**
For details, see [PyRS #2](https://code.ornl.gov/sns-hfir-scse/diffraction/engineering-diffraction/PyRS/-/issues/2#characterization-of-run-2250)

Sort points in scalar field according to (x, y, z) values

---

.github/workflows/ci.yml

This re-uses a bunch of work that was tested out with [addie](https://github.com/neutrons/addie) as far as determining the environment names and triggering gitlab.

Change to re-usable github-actions

---

.github/workflows/ci.yml
environment.yml

[boa](https://github.com/mamba-org/boa) uses the dependency solver from mamba which is the longest step of creating this conda package.

Switch to boa for building

---

pyrs/core/nexus_conversion.py

commit change for how time averaged data are pulled from logs

---

pyrs/interface/peak_fitting/event_handler.py
pyrs/interface/peak_fitting/export.py

disable export fitting when no file is loaded

---

pyrs/calibration/mantid_peakfit_calibration.py
pyrs/core/monosetting.py
pyrs/core/nexus_conversion.py
pyrs/core/reduce_hb2b_pyrs.py
pyrs/dataobjects/fields.py
pyrs/peaks/peak_fit_engine.py
tests/integration/test_powder_pattern.py

inital address test warnings
