neutrons/PyRS

designer/peakfitplotcontrol.ui, designer/peakfitwindow.ui, designer/texturecalculationwindow.ui, designer/texturereductionsetupwindow.ui, docs/README.md, pyrs/core/datamanagers.py, pyrs/core/mantid_fit_peak.py, pyrs/core/pyrscore.py, pyrs/core/rshelper.py, pyrs/core/scandataio.py, pyrs/interface/fitpeakswindow.py, pyrs/interface/gui_helper.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/mplgraphicsview1d.py, pyrs/interface/ui/mplgraphicsview2d.py, pyrs/interface/ui/rstables.py, tests/guitest/peakfitgui_test.py, tests/unittest/pyrs_core_test.py
Improve peak fitting sub-module according to the feedback from demo. 
This fixes #3 and #4.
=> Improve peak fitting sub module for testing

designer/pyrsmain.ui, pyrs/core/pyrscore.py, pyrs/interface/textureanalysiswindow.py, pyrstest.sh, setup.py, tests/guitest/textureanalysisgui.py, tests/guitest/texturegui_test.py
=> Implement texture analysis UI

designer/gridsalignmentview.ui, designer/sscalvizwindow.ui, designer/strainstressview.ui, pyrs/core/pyrscore.py, pyrs/core/scandataio.py, pyrs/core/strain_stress_calculator.py, pyrs/interface/dialogs.py, pyrs/interface/gui_helper.py, pyrs/interface/pyrs_main.py, pyrs/interface/strainstresscalwindow.py, pyrs/interface/ui/rstables.py, pyrs/interface/ui/slice_view_widget.py, pyrs/interface/ui/sliceviewwidgets.py, pyrs/utilities/checkdatatypes.py, pyrs_gui_test.sh, tests/guitest/peakfitgui_test.py, tests/guitest/strainstressgui_test.py, tests/unittest/straincalculationtest.py
This fixes #20 and #22 and #23.
This also works on  #18 and #19.
=> Enhance user experience on strain/stress module

pyrs/core/mantid_fit_peak.py
=> Improve fitting peak with PseudoVoigt

prototypes/calibration/Quick_Calibration_Quasi_HB2B.py, prototypes/calibration/Quick_Calibration_general.py, prototypes/calibration/Quick_Calibration_v2.py, prototypes/calibration/Quick_Calibration_v3.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs_calibration.sh, pyrs_gui_test.sh, pyrs_reduce_study.sh, tests/unittest/reduction_study.py
=> Prototype of calibration

pyrs/core/reductionengine.py, pyrs/interface/calibrationwindow.py, pyrs/utilities/file_util.py, pyrs/utilities/rs_project_file.py, pyrs_command.sh, scripts/convert_hzb_data.py, scripts/convert_raw_data.py, scripts/reduce_HB2B.py, setup.py, tests/Quick_Calibration_v2.py, tests/testdata/hzb/HZB_Definition_20190523_0844.txt, tests/testdata/hzb/HZB_Definition_20190523_0844.xml, tests/unittest/compare_reduction_engines_test.py, tests/unittest/reduction_study.py, verify_pyrs_reduction.sh
It includes the work on HB2B project file I/O, peak fitting and instrument calibration prototype (model).
HZB data will be used to
1. demo re-reduction
1. demo peak fitting
It tends to fix #49 and #55.
It fixes #55.
It fixes part of #49.
=> Testing with HZB data

designer/manualreductionwindow.ui, pyrs/core/reductionengine.py, pyrs/interface/gui_helper.py, pyrs/interface/manualreductionwindow.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/mplgraphicsview1d.py, pyrs/utilities/rs_project_file.py, scripts/reduce_HB2B.py
**Summary**
1. Re-reduction UI is improved
1. Re-reduction UI is enabled to load Hidra project file
1. Re-reduction UI and back end are enabled to reduce data from Hidra project file
1. Re-reduction UI and back end are enabled to plot raw counts and reduced diffraction pattern
1. Re-reduction UI and back end are enabled to save the reduced data to Hidra project
This fixes #60.
This fixed #32.
=> Implement Re-reduction UI

pyrs/core/mantid_fit_peak.py, pyrs/interface/fitpeakswindow.py, pyrs/interface/gui_helper.py, pyrs/interface/ui/NTableWidget.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/mplfitplottingwidget.py, pyrs/interface/ui/rstables.py, pyrs_gui_test.sh, setup.py, tests/guitest/manualreduction_test.py, tests/guitest/peakfitgui_test.py
=> Revisit peak fitting for touchbase demo

designer/ManualSlicerTable.ui, designer/README.txt, designer/eventslicersetupwindow.ui, designer/gridsalignmentview.ui, designer/peakfitplotcontrol.ui, designer/peakfitwindow.ui, designer/sscalvizwindow.ui, designer/strainstressview.ui, designer/texturecalculationwindow.ui, designer/texturereductionsetupwindow.ui, pyrs/interface/advpeakfitdialog.py, pyrs/interface/calibrationwindow.py, pyrs/interface/dialogs.py, pyrs/interface/fitpeakswindow.py, pyrs/interface/manualreductionwindow.py, pyrs/interface/pyrs_main.py, pyrs/interface/slicersetupwindow.py, pyrs/interface/strainstresscalwindow.py, pyrs/interface/textureanalysiswindow.py, pyrs/interface/ui/qt_util.py, pyrs/interface/ui/uitest_test_slice_view.py, pyrs/interface/ui/workspaceviewwidget.py, pyrsdevel.sh, setup.py
=> Enable PyRS to compile PyQt UI files dynamically

pyrsdevel.sh, scripts/pyrsplot
In order for PyRS to launch on node14 and node16.
=> Fix conflict of import PyQt4 and PyQt5

pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py, tests/unittest/reduction_test.py
=> Improve reduction functional test

pyrs/core/reduce_hb2b_mtd.py, pyrs/core/reduction_manager.py, tests/unittest/reduction_test.py
Make the test result output more informative.
=> Improve the reduction unit test

pyrs/__init__.py, pyrs/interface/ui/slice_view_widget.py, pyrsdevel.sh, setup.py, src/pyrs/__init__.py
This fills in the rest of versioneer configuration moves more work over to setuptools.
=> Fix setup.py

pyrs/interface/advpeakfitdialog.py, pyrs/interface/calibrationwindow.py, pyrs/interface/dialogs.py, pyrs/interface/fitpeakswindow.py, pyrs/interface/gui_helper.py, pyrs/interface/manualreductionwindow.py, pyrs/interface/pyrs_main.py, pyrs/interface/slicersetupwindow.py, pyrs/interface/strainstresscalwindow.py, pyrs/interface/textureanalysiswindow.py, pyrs/interface/ui/NTableWidget.py, pyrs/interface/ui/eventslicesetupwidgets.py, pyrs/interface/ui/mplfitplottingwidget.py, pyrs/interface/ui/mplgraphicsview.py, pyrs/interface/ui/mplgraphicsview1d.py, pyrs/interface/ui/mplgraphicsview2d.py, pyrs/interface/ui/mplgraphicsviewpolar.py, pyrs/interface/ui/qt_util.py, pyrs/interface/ui/slice_view_widget.py, pyrs/interface/ui/sliceviewwidgets.py, pyrs/interface/ui/workspaceviewwidget.py, scripts/pyrsplot
Removed all the commented out import (done during qtpy conversion)
Removed misplaced and empty README file
=> Clean qtpy conversion

pyrs/core/mantid_helper.py, pyrs/core/reduce_hb2b_mtd.py, pyrs/core/strain_stress_calculator.py, pyrs/interface/ui/sliceviewwidgets.py, pyrs/utilities/rs_scan_io.py, tests/unittest/prototype_reduction_test.py, tests/unittest/scandataio_test.py
UI does start.
Signed-off-by: JeanBilheux <bilheuxjm@ornl.gov>
=> strain and stree window now starts.

pyrs/core/calibration_manager.py, pyrs/core/instrument_geometry.py, pyrs/core/mantid_fit_peak.py, pyrs/core/mantid_helper.py, pyrs/core/mask_util.py, pyrs/core/peak_fit_engine.py, pyrs/core/peak_profile_utility.py, pyrs/core/pyrscore.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py, pyrs/core/scipypeakfitengine.py, pyrs/core/strain_stress_calculator.py, pyrs/core/workspaces.py, pyrs/interface/fitpeakswindow.py, pyrs/interface/manualreductionwindow.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/mplgraphicsview1d.py
As title
But H401,H404,H405,H306,H101
=> Reduce flake8 warnings

pyrs/core/reduction_manager.py, pyrs/interface/fitpeakswindow.py, pyrs/interface/manualreductionwindow.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/rstables.py, pyrs/utilities/rs_project_file.py, scripts/reduce_HB2B.py
This works with #95.
Also corresponding codes will be cleaned to reduce flake8 and pylint warnings (excluding H401,H404,H405,H306,H101, H301)
=> Improve auto and manual reduction

pyrs/interface/ui/NTableWidget.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/eventslicesetupwidgets.py, pyrs/interface/ui/mantidipythonwidget.py, pyrs/interface/ui/mplconstants.py, pyrs/interface/ui/mplfitplottingwidget.py, pyrs/interface/ui/mplgraphicsview.py, pyrs/interface/ui/mplgraphicsview1d.py, pyrs/interface/ui/mplgraphicsview2d.py, pyrs/interface/ui/mplgraphicsviewpolar.py, pyrs/interface/ui/rstables.py, pyrs/interface/ui/slice_view_widget.py, pyrs/interface/ui/sliceviewwidgets.py, pyrs/interface/ui/workspaceviewwidget.py, scripts/pyrscalibration.py
This moves to mantid's shim for matplotlib, moves the line style constants into a separate file, and fixes a bunch of flake8 warnings.
=> Matplotlib shim

pyrs/interface/ui/NTableWidget.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/eventslicesetupwidgets.py, pyrs/interface/ui/mantidipythonwidget.py, pyrs/interface/ui/mplgraphicsview.py, pyrs/interface/ui/mplgraphicsview1d.py, pyrs/interface/ui/mplgraphicsview2d.py, pyrs/interface/ui/mplgraphicsviewpolar.py, pyrs/interface/ui/rstables.py, pyrs/interface/ui/slice_view_widget.py, pyrs/interface/ui/sliceviewwidgets.py, pyrs/interface/ui/workspaceviewwidget.py
No including H401,H404,H405,H101,H306,H301
=> Reducing flake8 in interface/ui

pyrs/core/mantid_fit_peak.py, pyrs/core/peak_fit_engine.py, pyrs/core/peak_profile_utility.py, tests/integration/test_fit_peaks.py, tests/unit/test_peak_fit_engine.py
Including testing for effective parameters calculation for Gaussian and PseudoVoigt (#89)
=> Implement pytest for peak fitting

pyrs/utilities/rs_project_file.py, tests/unit/test_hidra_project_file.py
This PR is supposed to fix #87 and #89.
=> Peak parameter 

pyrstest.sh, scripts/reduce_HB2B.py, verify_pyrs_reduction.sh
First round of changes
Refs #85 and #88
=> Manual reduction script cleanup

pyrs/utilities/rs_project_file.py, tests/unit/test_hidra_project_file.py, tests/unit/test_pyrs_core.py
=> Peak parameter R/W from HiDRA project file

pyrs/core/nexus_conversion.py, pyrs/core/workspaces.py
Enable the conversion script to export sample logs from split workspace to HiDRA project file.
=> Fixed the issue to add sample logs to workspace and project file

pyrs/core/nexus_conversion.py, pyrs/core/workspaces.py, pyrs/utilities/rs_project_file.py
It fixes #134.
The inconsistency is observed between HidraWorkspace._sample_log_dict and HidrProjectFile
=> Make sample log read/write consistency

pyrs/core/nexus_conversion.py, pyrs/core/powder_pattern.py, pyrs/core/reduce_hb2b_mtd.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py, pyrs/core/workspaces.py, pyrs/utilities/checkdatatypes.py, pyrs/utilities/rs_project_file.py, tests/integration/test_autoreduction.py, tests/integration/test_project_file_rw.py, tests/integration/test_reduction.py
=> Test vanadium calibration

.travis.yml, pylint.sh
... and add a shell script to run it with some standardized options.
=> Remove pylint from buildscript

pyrs/calibration/peakfit_calibration.py
Converted calibration from lmfit to scipy. Added error check to use least_squares vs leastsq. Added intermediate function to handle switch between least_squares and leastsq.
=> Updated detector calibration

pyrs/calibration/peakfit_calibration.py, pyrs/core/nexus_conversion.py, pyrs/core/peak_fit_engine.py, pyrs/core/pyrscore.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py, pyrs/core/strain_stress_calculator.py, pyrs/core/workspaces.py, pyrs/utilities/checkdatatypes.py, pyrs/utilities/rs_project_file.py, scripts/preparetest/convert_hb2b_peaks.py, scripts/preparetest/convert_hzb_data.py, tests/data/convert_xray_data.py, tests/integration/test_fit_peaks.py, tests/integration/test_project_file_rw.py, tests/unit/test_hidra_project_file.py
The majority of this was changing all of the accessors/mutators to have the names `read_...`, `write_...` and `append_...` to better describe what they actually do.
=> Pay off debt in Project file

pyrs/core/reduction_manager.py, pyrs/interface/fitpeakswindow.py
Fix issues with real HiDRA data.
=> Bugfix: Peak fit ui

pyrs/core/mantid_fit_peak.py, pyrs/core/mantid_helper.py, pyrs/core/peak_collection.py, pyrs/core/peak_fit_engine.py, pyrs/core/peak_profile_utility.py, pyrs/core/pyrscore.py, pyrs/core/workspaces.py, pyrs/utilities/rs_project_file.py, tests/integration/test_fit_peaks.py, tests/unit/test_hidra_project_file.py, tests/unit/test_peak_fit_engine.py, tests/unit/test_pyrs_core.py
This PR starts as 
```
Starting new branch for strain/stress calculation.
```
But it is changed to create **PeakCollection** class to organize the peak parameters for multiple peaks use case, which did not exist from HB2B in previous life.
=> Create PeakCollection class to store peaks

pyrs/core/mantid_fit_peak.py, pyrs/core/nexus_conversion.py, pyrs/core/workspaces.py, pyrs/dataobjects.py, pyrs/utilities/rs_project_file.py, tests/unit/test_sample_logs.py
This is basically a fancy version of a `dict` that handles the slicing and matching in a single place.
=> Create a SampleLog object

pyrs/core/mantid_fit_peak.py, pyrs/core/peak_collection.py
Setting the values of the `PeakCollection` to nan wasn't working. This sets them individually.
=> Peak collection fix

pyrs/core/nexus_conversion.py, tests/integration/test_autoreduction.py, tests/unit/test_sample_logs.py
=> Fixed the time average issue in PyRS.

pyrs/core/nexus_conversion.py, pyrs/core/reduce_hb2b_pyrs.py, scripts/reduce_HB2B.py, tests/integration/test_autoreduction.py
As title, when PyRS splits the NeXus file to sub runs.
=> Enable user to specify the starting time for  event splitting

pyrs/core/peak_collection.py, pyrs/core/pyrscore.py, pyrs/core/reduction_manager.py, pyrs/core/summary_generator.py, pyrs/core/workspaces.py, pyrs/dataobjects.py, pyrs/utilities/rs_project_file.py, tests/integration/test_peak_fitting.py, tests/unit/test_hidra_project_file.py, tests/unit/test_sample_logs.py
This should meet the requirement of writing out the CSV file.
Fixes #97
=> Export csv file

pyrs/core/nexus_conversion.py, pyrs/utilities/rs_project_file.py, tests/integration/test_autoreduction.py
=> Enable nexus conversion to calculate duration of each sub run

pyrs/core/nexus_conversion.py, pyrs/core/workspaces.py, pyrs/utilities/rs_project_file.py
This was originally intended to improve the performance, which didn't happen, but the code is easier to follow now.
=> Code cleanup in nexus conversion

pyrs/core/mantid_fit_peak.py, pyrs/core/mantid_helper.py, pyrs/core/peak_collection.py, pyrs/core/peak_fit_engine.py, pyrs/core/peak_profile_utility.py, pyrs/core/pyrscore.py, pyrs/core/workspaces.py, pyrs/interface/peak_fitting/plot.py, tests/integration/test_peak_fitting.py
=> Improve peak fitting qualithy

pyrs/core/nexus_conversion.py, pyrs/core/powder_pattern.py, pyrs/core/reduction_manager.py
=> Refactor the method to convert counts to array.

pyrs/core/summary_generator.py, pyrs/dataobjects/sample_logs.py, tests/integration/test_peak_fitting.py, tests/unit/test_sample_logs.py
=> Check for strings being constant as well

pyrs/core/nexus_conversion.py, pyrs/core/powder_pattern.py, pyrs/nexus/split_sub_runs.py, tests/integration/test_reduction.py, tests/performance/test_convert_nexus.py
=> Enable new sub run algorithms to support mask

prototypes/load_split_subruns_numpy.py, pyrs/core/nexus_conversion.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py, pyrs/dataobjects/sample_logs.py, pyrs/interface/manual_reduction/manualreductionwindow.py, pyrs/split_sub_runs/load_split_sub_runs.py, scripts/reduce_HB2B.py, tests/integration/test_autoreduction.py, tests/integration/test_reduction.py, tests/performance/test_convert_nexus.py
=> Apply new event filtering method

pyrs/core/mantid_helper.py, pyrs/core/pyrscore.py, pyrs/peaks/fit_factory.py, pyrs/peaks/mantid_fit_peak.py, pyrs/peaks/peak_fit_engine.py, tests/integration/test_peak_fitting.py, tests/unit/test_peak_fit_engine.py
The idea is to simplify the API significantly so clients don't need to interact with so many things.
=> Change interface for PeakFitEngine

pyrs/core/mantid_helper.py, pyrs/core/pyrscore.py, pyrs/core/workspaces.py, pyrs/dataobjects/sample_logs.py, pyrs/peaks/fit_factory.py, pyrs/peaks/mantid_fit_peak.py, pyrs/peaks/peak_fit_engine.py, tests/integration/test_peak_fitting.py, tests/unit/test_peak_fit_engine.py
In preparation of other rework, convert the `SubRuns` into a formal object.
**Do not merge** until #259 has been because it contains those changes.
=> Move subruns into their own object

pyrs/core/nexus_conversion.py, pyrs/interface/manual_reduction/manualreductionwindow.py, scripts/reduce_HB2B.py, tests/integration/test_autoreduction.py, tests/integration/test_reduction.py
This is to fix the bug causing autoreduction failure.
=> Create default instrument inside nexus conversion

pyrs/interface/designer/manualreductionwindow.ui, pyrs/interface/manual_reduction/manualreductionwindow.py
Enable/disable line edit and push button objects depending on whether the default value is selected.
Set output directory using the relevant IPTS
=> Update Manual Reduction UI

tests/unit/test_peak_fit_engine.py
Fitting parameters are tested
**Do not merge before** #259
=> adding the test for fitting parameters

pyrs/core/peak_profile_utility.py, pyrs/core/summary_generator.py, pyrs/dataobjects/sample_logs.py, pyrs/peaks/peak_collection.py, pyrs/projectfile/file_object.py, tests/integration/test_peak_fitting.py, tests/unit/test_hidra_project_file.py, tests/unit/test_peak_collection.py, tests/unit/test_peak_fit_engine.py
Simplify how callers get information about the peak fit results and related changes.
=> PeakCollection refactor

pyrs/peaks/mantid_fit_peak.py, pyrs/peaks/peak_fit_engine.py, tests/unit/test_peak_fit_engine.py
Try getting the peak center from each subrun by one of three methods (first one wins):
1. First moment of the data within the window
2. x-value of the maximum y-valuu in the window
3. Center value of the window
=> Fit engine guess center

.travis.yml
=> Add python 3 build to travis and allow it to fail

pyrs/calibration/peakfit_calibration.py, pyrs/interface/gui_helper.py, pyrs/interface/peak_fitting/plot.py, pyrs/interface/slicersetupwindow.py, pyrs/interface/strain_stress_calculation/strainstresscalwindow.py, pyrs/interface/ui/mantidipythonwidget.py, pyrs/utilities/checkdatatypes.py, pyrs/utilities/rs_scan_io.py, scripts/pyrs_calibration.py, tests/data/scripts/generate_slice_view_data.py, tests/unit/test_utilities.py
=> Fix python 3 flake8 warnings and errors

pyrs/interface/manual_reduction/pyrs_api.py
Force archive search to be always on
=> GetIPTS bugfix

.travis.yml, pyrs/core/peak_profile_utility.py, pyrs/core/reduction_manager.py, pyrs/core/summary_generator.py, pyrs/core/workspaces.py, pyrs/dataobjects/sample_logs.py, pyrs/projectfile/file_object.py, pyrs/split_sub_runs/load_split_sub_runs.py, pyrs/utilities/checkdatatypes.py, pyrs/utilities/file_util.py, tests/integration/test_peak_fitting.py, tests/unit/test_hidra_project_file.py
=> Fix tests for python 3

tests/integration/test_autoreduction.py, tests/integration/test_load_split.py
Also move empty file check into its own test
=> Use the ORIG version of nexus file when possible

pyrs/core/nexus_conversion.py, pyrs/split_sub_runs/load_split_sub_runs.py, tests/unit/test_sample_logs.py
This is a follow on to previous refactor work. Now the "old code" is getting significantly smaller functionality due to decreased use.
Refs #268
=> Remove unused code

pyrs/interface/advpeakfitdialog.py, pyrs/interface/dialogs.py, pyrs/interface/pyrs_main.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/rstables.py, pyrs/interface/ui/slice_view_widget.py, pyrs/interface/ui/workspaceviewwidget.py, pyrs/utilities/hb2b_utilities.py
=> Get the UI working in python 3

pyrs/core/powder_pattern.py, pyrs/core/workspaces.py, pyrs/interface/designer/manualreductionwindow.ui, pyrs/interface/manual_reduction/manualreductionwindow.py, pyrs/interface/manual_reduction/pyrs_api.py, pyrs/interface/ui/mplgraphicsview1d.py, pyrs/projectfile/file_object.py, pyrs/utilities/calibration_file_io.py, tests/integration/test_autoreduction.py, tests/integration/test_load_split.py, tests/unit/test_hidra_project_file.py
=> Verify geometry calibration R/W

pyrs/core/summary_generator.py, pyrs/peaks/peak_collection.py, tests/integration/test_peak_fitting.py, tests/unit/test_peak_collection.py
added "dspacing center"
Fixes #318
=> Add wavelength to PeakCollection

pyrs/core/powder_pattern.py, pyrs/core/reduce_hb2b_pyrs.py, scripts/reduce_HB2B.py
=> Enable reduce_hb2b.py to save counts as an option.

pyrs/interface/designer/manualreductionwindow.ui, pyrs/interface/manual_reduction/event_handler.py, pyrs/interface/manual_reduction/manualreductionwindow.py, pyrs/interface/manual_reduction/pyrs_api.py, tests/integration/test_manual_reduction_ui.py
=> Enable vanadium correction in manual reduction UI

pyrs/peaks/peak_collection.py, tests/unit/test_peak_collection.py
=>  strain calculation and associate test

pyrs/core/summary_generator.py, tests/integration/test_manual_reduction_ui.py, tests/integration/test_peak_fitting.py, tests/unit/test_peak_fit_engine.py
Small issues built up on python3 testing
Refs #337
=> Python3 fixes

pyrs/interface/peak_fitting/fit.py, pyrs/peaks/fit_factory.py, pyrs/peaks/mantid_fit_peak.py, pyrs/peaks/peak_fit_engine.py, tests/unit/test_peak_fit_engine.py
This was a missing connection to allow for strain calculations
=> Add wavelength to PeakCollection when fitting

pyrs/peaks/peak_collection.py, tests/unit/test_peak_collection.py
Also change test values for the peak center to be more physical to aid
in determining whether they are correct.
=> Fix error in calculation of d-spacing from 2theta

pyrs/calibration/peakfit_calibration.py, pyrs/core/__init__.py, pyrs/core/monosetting.py, pyrs/core/nexus_conversion.py, tests/integration/test_calibration_class.py, tests/unit/test_monosetting.py
This adds the Monosetting Enum to obtain an approximate wavelength from the monochromator rotation angle
Fixes #380
=> Monosetting enum

pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py, pyrs/core/workspaces.py, tests/integration/test_powder_pattern.py
Reverts neutrons/PyRS#285 which broke `master`. This is likely because of the bugfix in #360.
=> Revert "Refactor workflow to calculate powder pattern by PyRS routine"

pyrs/interface/ui/mplfitplottingwidget.py, pyrs/interface/ui/mplgraphicsview1d.py
There is a dict involved in all of the plotting which is being updated during deleting lines. This "fixes" the ones I came across.
Refs #288
=> Add temporary fixes to get rid of python3 issues

pyrs/dataobjects/constants.py, pyrs/interface/designer/manualreductionwindow.ui, pyrs/interface/manual_reduction/event_handler.py, pyrs/interface/manual_reduction/manualreductionwindow.py, pyrs/interface/manual_reduction/pyrs_api.py, pyrs/peaks/peak_collection.py, pyrs/projectfile/file_object.py, tests/unit/test_hidra_project_file.py
This fixes #361.
This fixes #362.
This fixes #391.
=> Enable PeakCollection to read and write d-reference from HiDRA project file

.travis.yml, pyrs/core/summary_generator.py, tests/integration/test_peak_fitting.py
Add strain to csv file
fixes #363
=> add strain to csv file and associate test

pyrs/core/powder_pattern.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py
Option to load vanadium nexus file. Modified order of operation for normalization by vanadium duration to enable propagation of error if data are normalized by vanadium.
=> Autoreduce vanadium

.travis.yml, launch_pyrs.sh, pylint.sh, pyrs/core/instrument_geometry.py, pyrs/core/nexus_conversion.py, pyrs/interface/ui/mplgraphicsview1d.py, pyrsdevel.sh, pyrstest.sh, setup.py, tests/unit/test_utilities.py
In an attempt to make builds work again. Drop python2.
=> Drop python2 from builds

pyrs/core/reduce_hb2b_pyrs.py, tests/integration/test_powder_pattern.py
=> Refactor workflow to calculate powder pattern by PyRS routine

pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/reduction_manager.py
I added a check in to reuse the last reduction engine (with built instrument) if the 2theta does not change between scan_index
Refactor of #408 after rebase with master
=> Refactor Increase_Reduction_Speed after rebase with master

pyrs/core/reduction_manager.py, tests/integration/test_texture_reduction.py
Changed the eta masking scheme to work for both mantid and pyrs engines.
=> Added check to switch out of plan masking between pyrs and mantid

README.rst
I added a short developer quick start section to the readme.
=> Develop quick start section in the README

scripts/development/setup.sh
Run and provide username
Configures upstream (neutrons/PyRS) and origin (your fork) repos
=> First-time development script

.travis.yml, pyrs/core/instrument_geometry.py, pyrs/core/mask_util.py, pyrs/core/polefigurecalculator.py, pyrs/core/reduction_manager.py, pyrs/core/strain_stress_calculator.py, pyrs/core/workspaces.py, pyrs/projectfile/file_object.py, pyrs/utilities/checkdatatypes.py, pyrs/utilities/convertdatatypes.py, pyrs/utilities/hb2b_utilities.py, scripts/create_mask.py, tests/integration/test_calibration_class.py, tests/integration/test_peak_fitting.py, tests/integration/test_powder_pattern.py, tests/integration/test_project_file_rw.py, tests/integration/test_reduction.py, tests/unit/test_converters.py
This moves much of the type checking to the builds by adding type hints and forceably converting things to integers when required.
=> Replace Checkdatatypes.check_int_value

pyrs/core/strain_stress_calculator.py
=> intial refactor for calculating stress

.travis.yml, README.rst, codecov.yaml, conda.recipe/meta.yaml
Add pytest-cov in conda recipe
Add codecov badge in README
=> Add code coverage on CI with pytest-cov and upload to codecov

pyrs/core/strain_stress_calculator.py, pyrs/core/summary_generator.py, pyrs/interface/peak_fitting/data_retriever.py, pyrs/interface/peak_fitting/fit_table.py, pyrs/peaks/peak_collection.py, tests/unit/test_peak_collection.py
=> Change from strain to microstrain

.travis.yml, pyrs/dataobjects/constants.py, pyrs/peaks/peak_collection.py, pyrs/projectfile/file_object.py, tests/unit/test_hidra_project_file.py, tests/unit/test_peak_collection.py
=> Optional uncertainty in d-reference

.travis.yml, pyrs/calibration/peakfit_calibration.py
The calibration code no longer needs to support older scipy
=> Remove support for legacy scipy

docs/planning/RSE_UserStoryTemplate.md, docs/planning/UserStoryConcepts.md
=> Add User stories documentation

pyrs/core/strain_stress_calculator.py, pyrs/core/summary_generator.py, pyrs/interface/peak_fitting/data_retriever.py, pyrs/interface/peak_fitting/fit_table.py, pyrs/peaks/peak_collection.py, tests/unit/test_peak_collection.py
=> Add option to select units of strain

pyrs/core/strain_stress_calculator.py, tests/unit/test_hidra_project_file.py, tests/unit/test_load_split.py, tests/unit/test_monosetting.py, tests/unit/test_peak_collection.py, tests/unit/test_peak_fit_engine.py, tests/unit/test_sample_logs.py, tests/unit/test_toMD.py, tests/unit/test_utilities.py
This will allow for code/tests to be written against the proper data object.
Refs #427
=> Add code to convert data to MDHisto workspace

pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> Refs #470 

reduce_HB2B.sh
This is the one script that is looking at the old version of the python script
=> Change which build directory to look at

pyrs/dataobjects/constants.py, pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> Scalar field

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Export ScalarFieldSample to MDHistoWorkspace

pyrs/core/strain_stress_calculator.py, pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Generate scalar strain field

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> 484 stack scalar fields samples

README.rst
=> Added information for running tests

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> Interpolator method for ScalarField

pyrs.sh, pyrs/dataobjects/fields.py
First I need to move to using mantid nightly, second change the way the MD workspace is collected so there is no Original Workspace on the MDHistoWorkspace
Fixes #504
=> Fix Strain/Stress Viewer running on analysis

pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
Also simplify how the internal data is exposed through public functions
=> Refactor PointList to use ndarray underneath

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/integration/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Integration test: fuse ScalarFieldSample objects

tests/unit/pyrs/dataobjects/test_fields.py
Not all of the tests were verifying results.
=> Add assertions to tests in fields

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
This currently only handles the simple case of all of the `StrainField` objects having identical `PointList` objects. 
Refs #427
=> Add StressField object

tests/conftest.py, tests/unit/pyrs/dataobjects/test_fields.py
=> unit test_stack_scalar_field_samples failing

pyrs/interface/ui/mplgraphicsview1d.py
Addresses #490 
Just a bounds check.
Working with `pyrsplot`
TODO: more bounds checks and tests.
=> Patch for bounds check in 1D peak fitting cases

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> Detect if the PointList represents a regular grid

pyrs/dataobjects/fields.py, pyrs/interface/strainstressviewer/controller.py, pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Connect "Calculate Stress/Strain" button to calculate Stress

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Store Young Modulus and Poisson Ratio in class StressField -

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> Interpolate linear scans

pyrs/dataobjects/fields.py, pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py, pyrs/peaks/peak_collection.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Add viewing of other peak parameters to Strain/Stress viewer

pyrs/interface/peak_fitting/event_handler.py, pyrs/interface/peak_fitting/fitpeakswindow.py
The Save As... option in the Peak Fitting window will now appropriately
allow to the saving of a new file.
Addresses #513
Signed-off-by: Robert Smith <smithrw@ornl.gov>
=> Added Save As to Peak Fitting

pyrs/interface/strainstressviewer/controller.py, pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py
This add validation to required inputs before attempting to plot and will update Stress plot anytime a input is changed
=> Remove Calculate stress button and calculate stress on demand

pyrs/dataobjects/sample_logs.py, tests/integration/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> Integration test: interpolate ScalarFieldSample

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Add StrainField member reference to peak_collection

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Implement ScalarFieldSample.clone( )

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Add StrainField per direction references in StressField class

pyrs/dataobjects/fields.py, tests/conftest.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Switch from StrainField is a ScalarFieldSample to StrainField has a ScalarFieldSample

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Fuse two strain fields measured along the same direction

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Fuse two or more strain fields measured along the same direction #566

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Stack two strain fields measured along different directions #568

pyrs/dataobjects/fields.py
=> Switch back from StressField has a ScalarFieldSample to StressField is a ScalarFieldSample

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> StressField `get_strain` function to match object direction state

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Add filenames StrainField came from

pyrs/dataobjects/fields.py, tests/conftest.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Overload __add__ and __mul__ for ScalarFieldSample

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Calculate ε33 for in-plane stress case

tests/unit/pyrs/dataobjects/test_fields.py
All of the strains are the same, so this is a super easy test to pass.
Fixes #526
=> Add test for creating StressField from files

tests/integration/pyrs/dataobjects/test_fields.py
=> Add test data for multiple project files combining into a single StrainField

pyrs/core/workspaces.py, pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, pyrs/peaks/peak_collection.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/test_peak_collection.py, tests/unit/test_sample_logs.py
This has various changes to let composition handle the work of calculating things.
Refs #525
=> Refactor StrainField to more directly use PointList

pyrs/core/workspaces.py, pyrs/peaks/mantid_fit_peak.py, pyrs/peaks/peak_collection.py, pyrs/peaks/peak_fit_engine.py, pyrs/projectfile/file_object.py, tests/unit/test_peak_collection.py
To make #451 easier to implement. Add the project file and run number to the `PeakCollection`
=> Peak collection filenames

pyrs/dataobjects/fields.py
=> fields module docstring

docs/planning/UserStory_GridInformation_CSVOutputs.md, docs/planning/UserStory_PeakInformation_CSVOutputs.md
Signed-off-by: Jose Borreguero <borreguero@gmail.com>
=> User Stories for CSV Outputs

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/integration/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
Work done:
- remove optional units and hardcode 'meter'
- Insert factor 10^-3 when exporting to MDHistoWorkspace
Closes #534
=> to_md_histo_workspace gives wrong units

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/integration/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
=> Export to MDHistoWorkspace in milimeters

pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py, tests/ui/test_stress_strain_viewer.py
=> Add peak measurement point overlay in Strain/Stress viewer

pyrs/dataobjects/sample_logs.py
=> Refs #633 add docs

pyrs/interface/strainstressviewer/strain_stress_view.py
=> Fix 1D plot in Stress/Strain viewer for older version of mpl

pyrs/interface/designer/peakfitwindow.ui
=> Peak fitting window, change Export CSV button name

pyrs/dataobjects/sample_logs.py
=> docs for SampleLogs

pyrs/interface/designer/peakfitwindow.ui, pyrs/interface/peak_fitting/event_handler.py, pyrs/interface/peak_fitting/fitpeakswindow.py
=> Peak fitting UI - add loading by run number

pyrs/core/summary_generator_stress.py
Solve slowdown on writing CSV summary file
`PeakCollection` getters are not "cheap"
Refactoring, tests pass
=> Cache peak_collection getters outputs in writing CSV summary file

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
This adds methods for the effective peak information. The code has been re-factored to reduce the amount of duplicate code.
Fixes #525
=> StrainField add methods for getting effective peak parameters

pyrs/core/summary_generator_stress.py, tests/integration/test_write_stress_csv.py
=> Move nan check up front

pyrs/dataobjects/fields.py, pyrs/interface/strainstressviewer/controller.py, pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py, tests/ui/test_stress_strain_viewer.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Stress/Strain Viewer - allow loading multiple files

tests/conftest.py, tests/test_conftest.py
=> Refs #679 strain builder fixture and unit test

pyrs/dataobjects/fields.py, tests/unit/pyrs/dataobjects/test_fields.py
=> Add method to set d-reference on a StrainField

pyrs/core/stress_facade.py, pyrs/peaks/peak_collection.py, tests/conftest.py, tests/test_conftest.py, tests/unit/pyrs/dataobjects/test_strainstress.py
=> 661 strain stress facade, partial implementation

pyrs/dataobjects/fields.py
=> Promote values property to strains base class

pyrs/dataobjects/fields.py, pyrs/dataobjects/sample_logs.py, tests/unit/pyrs/dataobjects/test_sample_logs.py
Add a method to determine the indices where a positions in a `PointList` exist in another `PointList`.
Fixes #685
=> PointList.get_indices

pyrs/interface/strainstressviewer/controller.py, pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py, tests/ui/test_stress_strain_viewer.py
=> Improve using and updating StressField when values are changed

pyrs/interface/strainstressviewer/model.py
=> Stress UI catch errors from CSV writter

pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py, tests/ui/test_stress_strain_viewer.py
=> Add d0 grid to viewer with load and save to CSV

pyrs/dataobjects/fields.py, tests/conftest.py, tests/ui/test_stress_strain_viewer.py, tests/unit/pyrs/dataobjects/test_fields.py, tests/unit/pyrs/test_trigger.py
=> Investigate possible bug on StrainField.field upon stacking

pyrs/dataobjects/fields.py
=> Merge point_list and point_list_immutable for StrainFieldSingle

tests/ui/test_stress_strain_viewer.py
Change which data the test is using
=> Fix stress ui tests for stacking changes

pyrs/core/stress_facade.py, tests/unit/pyrs/core/test_stress_facade.py
=> Test StressFacade exports fit parameters to MDHistoWorkspace

pyrs/interface/pyrs_main.py, pyrs/interface/strainstressviewer/start.py, pyrs/interface/strainstressviewer/strain_stress_view.py, requirements.txt
Don't merge as this fails to run on analysis because of issues with OpenGL/VirtualGL that need to be resolved.
=> Add 3D view to Strain/Stress viewer

tests/conftest.py, tests/unit/test_peak_fit_engine.py
=> Remove test skip

tests/ui/test_stress_strain_viewer.py
=> Move to central ON_TRAVIS variable

pyrs/interface/strainstressviewer/controller.py, pyrs/interface/strainstressviewer/model.py, pyrs/interface/strainstressviewer/strain_stress_view.py, tests/ui/test_stress_strain_viewer.py
Fixes #522 and fixes #523 and fixes  #728
=> Stress/Strain Viewer - Add save state to file menu

pyrs/interface/gui_helper.py, pyrs/interface/strainstressviewer/strain_stress_view.py
So that the UI tests will run when using GNOME
=> Change QFileDialog to DontUseNativeDialog

pyrs/interface/gui_helper.py, pyrs/interface/manual_reduction/manualreductionwindow.py
=> Automatically plot on sub-run change

pyrs/utilities/calibration_file_io.py
=> Fix calib entry

pyrs/interface/peak_fitting/event_handler.py
=> Check for h5 extension when saving project file

pyrs/interface/peak_fitting/event_handler.py, pyrs/interface/peak_fitting/fitpeakswindow.py, pyrs/interface/peak_fitting/plot.py, setup.py, versioneer.py
fix UI handling for how to exclude sub_logs, 
Fixes #756
=> Fix exclude subrun parse

.travis.yml, pyrs/core/monosetting.py, tests/data/scripts/generate_slice_view_data.py
change range for automatic monosetting detection
=> changed range for monosetting

.github/workflows/ornl-dev.yml, .github/workflows/ornl-prod.yml
Added GitHub Actions to trigger GitLab CI/CD for deployments to ORNL Analysis Cluster
=> github actions for deployments

paper/paper.bib, paper/paper.md
@fanchercm I just added a few things to the JOSS paper PR for your review. Hope it helps.
Changes:
- Add authors ORCiD and affiliations
- Add bib reference to event data and HDF5
- Modify acknowledgement (funding)
- Minor changes: date, narrative
- Add definition to math symbols
=> Joss paper review

.github/workflows/ci.yml, conda.recipe/environment.yml, conda.recipe/meta.yaml, environment.yml, setup.py
=> Conda build

.github/workflows/ci.yml
removed anaconda deployment actions
=> added deployment action for next

.github/workflows/ci.yml
See iMars3D PR: https://github.com/ornlneutronimaging/iMars3D/pull/281/files
=> Trouble shoot CI failure related to Github mamba solution

.github/workflows/ci.yml
Update `branch-mapper` to use v2 instead of main.
=> update the action to v2

pyrs/core/nexus_conversion.py
=> patch for timeAverageValue

pyrs/interface/detector_calibration/detector_calibration_crtl.py, pyrs/interface/ui/diffdataviews.py, pyrs/interface/ui/mplgraphicsview1d.py
=> fix error with setting axis off

pyrs/interface/peak_fitting/load.py, pyrs/interface/peak_fitting/plot.py, pyrs/interface/texture_fitting/texture_fitting_crtl.py
=> fix for gui bugs

pyrs/core/nexus_conversion.py, pyrs/interface/peak_fitting/event_handler.py
=> fix for cancel save as

pyrs/core/nexus_conversion.py
=> added error handling for single subrun live data

pyrs/core/summary_generator.py, pyrs/core/summary_generator_stress.py, pyrs/dataobjects/constants.py, pyrs/dataobjects/fields.py, pyrs/interface/peak_fitting/data_retriever.py, pyrs/interface/peak_fitting/fit_table.py, pyrs/interface/strainstressviewer/model.py, pyrs/interface/ui/rstables.py, pyrs/peaks/peak_collection.py, pyrs/projectfile/file_object.py
=> Exclude points

pyrs/interface/detector_calibration/detector_calibration_crtl.py, pyrs/interface/detector_calibration/detector_calibration_viewer.py
=> fix calibration paramview

pyrs/interface/peak_fitting/data_retriever.py
=> fix exclude

pyrs/core/nexus_conversion.py
=> changed how time averaged data are pulled

pyrs/interface/peak_fitting/load.py
=> reset fit_results to catch error

conda.recipe/meta.yaml, environment.yml
=> removed vtk from environment file

conda.recipe/meta.yaml, environment.yml
=> fix vtk error for qa

pyrs/dataobjects/constants.py, pyrs/projectfile/file_object.py
=> added effective params to project file

pyrs/core/peak_profile_utility.py, pyrs/interface/designer/peakfitwindow.ui, pyrs/interface/peak_fitting/fit.py, pyrs/interface/texture_fitting/texture_fitting_crtl.py, pyrs/interface/texture_fitting/texture_fitting_viewer.py, pyrs/peaks/fit_factory.py, tests/integration/test_peak_fitting.py, tests/ui/test_peak_fitting.py, tests/unit/pyrs/core/test_stress_facade.py, tests/unit/pyrs/peaks/test_peak_collection.py, tests/unit/pyrs/peaks/test_peak_fit_engine.py
=> Add background peakshape

pyrs/interface/ui/mplfitplottingwidget.py
=> fix np NaN error

pyrs/dataobjects/sample_logs.py, pyrs/interface/peak_fitting/plot.py, pyrs/interface/texture_fitting/texture_fitting_viewer.py, tests/integration/test_write_stress_csv.py, tests/ui/test_texture_fitting.py, tests/unit/pyrs/peaks/test_peak_collection.py
=> inital commit to fix numpy20 errors

pyrs/calibration/mantid_peakfit_calibration.py, pyrs/core/monosetting.py, pyrs/core/nexus_conversion.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/workspaces.py, pyrs/dataobjects/fields.py, pyrs/peaks/mantid_fit_peak.py, pyrs/peaks/peak_fit_engine.py, tests/integration/test_powder_pattern.py
=> refactor to address test warnings

pyrs/calibration/mantid_peakfit_calibration.py, pyrs/core/monosetting.py, pyrs/core/nexus_conversion.py, pyrs/core/reduce_hb2b_pyrs.py, pyrs/core/workspaces.py, pyrs/dataobjects/fields.py, pyrs/peaks/mantid_fit_peak.py, pyrs/peaks/peak_fit_engine.py, tests/integration/test_powder_pattern.py
=> Fix test warning main

pyrs/interface/texture_fitting/texture_fitting_crtl.py
=> Fix texture UI warning

pyrs/interface/texture_fitting/texture_fitting_crtl.py
=> change how sub_run_index is pulled for UI

tests/unit/pyrs/peaks/test_peak_fit_engine.py
=> added try except to catch nonetype failure during testings

pyrs/interface/strainstressviewer/strain_stress_view.py
=> added check if on thinlic to skip vtk import

pyrs/core/summary_generator.py, pyrs/interface/peak_fitting/export.py, tests/integration/test_peak_fitting.py
=> added wavelength entry to csv summary

pyrs/core/summary_generator.py, pyrs/interface/peak_fitting/export.py, tests/integration/test_peak_fitting.py
=> Export wavelength next

pyrs/core/instrument_geometry.py, pyrs/core/summary_generator.py, pyrs/core/workspaces.py, pyrs/interface/peak_fitting/export.py, pyrs/utilities/calibration_file_io.py, tests/integration/test_peak_fitting.py, tests/ui/test_peak_fitting.py
=> added more information about mono setting to peaksummary export

pyrs/interface/peak_fitting/event_handler.py, tests/integration/test_load_split.py
=> fix for loading multiple runs

pyrs/core/nexus_conversion.py
=> fix unknow log name

pyrs/dataobjects/fields.py, pyrs/interface/strainstressviewer/strain_stress_view.py
=> Pyrs stress strain settings

pyrs/interface/strainstressviewer/strain_stress_view.py
=> modulate backend viewer to maining a constant color limit

pixi.lock, pyproject.toml
=> Ewm11587 upgrade mantid to 613

pyrs/core/monosetting.py, tests/unit/pyrs/core/test_monosetting.py
=> update mrot for new mono

pyrs/interface/peak_fitting/event_handler.py, pyrs/interface/peak_fitting/load.py
=> Fix runnumber save
